package codewithSuvro;

public class TWO {
    public static void main(String[] args) {
        //  BINARY SEARCH CRUCIAL POINTS :
        // 1] FIND THE MIDDLE ELEMENT
        // 2] CHECK IF THE TARGET ELEMENT > MIDDLE OR NOT
        // IF TARGET > MIDDLE - THEN THE TARGET ELEMENT WILL LIE ON THE RIGHT SIDE OF THE MIDDLE ELEMENT
        // IF THE TARGET ELEMENT IS GREATER THAN THE MIDDLE ELEMENT THEN THE START POINTER WILL BE
        // MIDDLE + 1
        // 3] IF THE TARGET ELEMENT IS < MIDDLE THEN IT TILL LIE ON THE LEFT SIDE OF THE MIDDLE ELEMENT
        // THEN END WILL BE MIDDLE -1
        // 4] CONDITION FOR LOOP STOP IS
        // WHEN THE START POINTER > END THEN THE ELEMENT IS NOT FOUND
        
    }
}
